
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 27 13:36:05 CEST 2022
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int UNIDADBOOL = 6;
  public static final int POR = 10;
  public static final int CCIERRE = 34;
  public static final int PCIERRE = 23;
  public static final int LCIERRE = 32;
  public static final int LAP = 31;
  public static final int CAP = 33;
  public static final int INT = 35;
  public static final int ARRAY = 40;
  public static final int SEPARADOR = 24;
  public static final int DELETE = 54;
  public static final int WRITE = 51;
  public static final int NUMENT = 2;
  public static final int NOT = 14;
  public static final int MENORIGUAL = 18;
  public static final int AND = 12;
  public static final int IGUAL = 7;
  public static final int RECORD = 41;
  public static final int TYPE = 27;
  public static final int OR = 13;
  public static final int BOOL = 3;
  public static final int CALL = 55;
  public static final int DIV = 11;
  public static final int IF = 43;
  public static final int ENDWHILE = 49;
  public static final int OF = 38;
  public static final int MAYORIGUAL = 17;
  public static final int EOF = 0;
  public static final int AMP = 30;
  public static final int NEW = 53;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int CADENA = 60;
  public static final int MODULO = 57;
  public static final int MENOS = 9;
  public static final int NULL = 39;
  public static final int MENOR = 16;
  public static final int IDENT = 26;
  public static final int PCOMA = 5;
  public static final int NUMREAL = 4;
  public static final int REAL = 36;
  public static final int MAYOR = 15;
  public static final int INDIRECCION = 59;
  public static final int PAP = 22;
  public static final int FLECHA = 56;
  public static final int ENDIF = 46;
  public static final int NEG = 21;
  public static final int ELSE = 44;
  public static final int PUNTO = 58;
  public static final int NL = 52;
  public static final int READ = 50;
  public static final int WHILE = 47;
  public static final int NOEQUIV = 20;
  public static final int EQUIV = 19;
  public static final int THEN = 45;
  public static final int STRING = 37;
  public static final int PROC = 28;
  public static final int POINTER = 42;
  public static final int VAR = 25;
  public static final int DO = 48;
  public static final int MAS = 8;
}

