package alex;

public enum ClaseLexica {
 IDEN, ENT, REAL, PAP, PCIERRE, IGUAL, COMA, 
 MAS, MENOS, POR, DIV, EOF, 
 BOOL, TENT, TREAL, TBOOL, MENOR, MAYOR,
 MENORI, MAYORI, IGIG , NOIG , NOT, AND, OR,
 PUNTOCOMA, SEPARADOR, CADENA, COMENTARIO, 
 MODULO, CAP, CCIERRE, LAP, LCIERRE, 
 PUNTO, FLECHA, AMPERSAND, TCADENA, NULL, 
 PROC, IF, THEN, ELSE, ENDIF, WHILE, DO, 
 ENDWHILE, CALL, RECORD, TARRAY, OF, TPOINTER,
 NEW, DELETE, READ, WRITE, NL, VAR, TYPE
}
